site_name: FSR Informatik

theme:
  language: de
  favicon: images/favicon.png
  logo: images/logo.png
  name: material
  font:
    text: Atkinson Hyperlegible Next
    code: Atkinson Hyperlegible Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

markdown_extensions:
  - toc:
      title: Inhalte
  - attr_list
  - md_in_html
  - admonition

plugins:
  - privacy
  - search

nav:
  - HOME: index.md
  - ERSTIS: erstis.md
  - E-KEYS: ekeys.md
  - KONTAKT: kontakt.md
  - AKTUELLES: aktuelles.md
  - APP: app.md
  - IMPRESSUM: impressum.md

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/fachschaftsrat_fb4
      name: Instagram
    - icon: fontawesome/brands/github
      link: https://www.github.com/Fachschaftsrat-Informatik-FH-Dortmund
      name: GitHub
    - icon: fontawesome/brands/google-play
      link: https://play.google.com/store/apps/details?id=de.fsrfb4.fb4
      name: FSR-App auf Google Play